--Fechando conexões do banco ALUGMAT para permitir exclusão
USE MASTER;

GO

ALTER DATABASE ALUGMAT SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

GO

ALTER DATABASE ALUGMAT SET SINGLE_USER;

GO

--Excluindo banco ALUGMAT
DROP DATABASE ALUGMAT;

GO

--Criando banco ALUGMAT
CREATE DATABASE ALUGMAT;

GO

USE ALUGMAT;

GO

--Executar a partir desse ponto se não for necessário excluir o banco, mas sim algumas tabelas
DROP TABLE PERFIL;

GO

CREATE TABLE PERFIL (
ID INT PRIMARY KEY IDENTITY,
DATA_INC DATETIME,
DATA_ALT DATETIME,
STATUS CHAR(1),
MARCA CHAR(1),
OCULTAR CHAR(1),
PER_DESCRICAO VARCHAR(50),
PER_USUARIO CHAR(1),
PER_USUARIO_I CHAR(1),
PER_USUARIO_A CHAR(1),
PER_USUARIO_E CHAR(1),
PER_PERFIL CHAR(1),
PER_PERFIL_I CHAR(1),
PER_PERFIL_A CHAR(1),
PER_PERFIL_E CHAR(1),
PER_MARCA CHAR(1),
PER_MARCA_I CHAR(1),
PER_MARCA_A CHAR(1),
PER_MARCA_E CHAR(1),
PER_CATEGORIA CHAR(1),
PER_CATEGORIA_I CHAR(1),
PER_CATEGORIA_A CHAR(1),
PER_CATEGORIA_E CHAR(1),
PER_FORNECEDOR CHAR(1),
PER_FORNECEDOR_I CHAR(1),
PER_FORNECEDOR_A CHAR(1),
PER_FORNECEDOR_E CHAR(1),
PER_PRODUTO CHAR(1),
PER_PRODUTO_I CHAR(1),
PER_PRODUTO_A CHAR(1),
PER_PRODUTO_E CHAR(1),
PER_CLIENTE CHAR(1),
PER_CLIENTE_I CHAR(1),
PER_CLIENTE_A CHAR(1),
PER_CLIENTE_E CHAR(1),
PER_ALUGUEL CHAR(1),
PER_ALUGUEL_I CHAR(1),
PER_ALUGUEL_A CHAR(1),
PER_ALUGUEL_E CHAR(1)
)

GO

--Inserindo Perfil para teste com todas as permissões liberadas
INSERT INTO PERFIL (STATUS, PER_DESCRICAO, PER_USUARIO,PER_USUARIO_I,PER_USUARIO_A,PER_USUARIO_E,PER_PERFIL,PER_PERFIL_I,PER_PERFIL_A,PER_PERFIL_E,PER_MARCA,PER_MARCA_I,PER_MARCA_A,PER_MARCA_E,PER_CATEGORIA,PER_CATEGORIA_I,PER_CATEGORIA_A,PER_CATEGORIA_E,PER_FORNECEDOR,PER_FORNECEDOR_I,PER_FORNECEDOR_A,PER_FORNECEDOR_E,PER_PRODUTO,PER_PRODUTO_I,PER_PRODUTO_A,PER_PRODUTO_E,PER_CLIENTE,PER_CLIENTE_I,PER_CLIENTE_A,PER_CLIENTE_E,PER_ALUGUEL,PER_ALUGUEL_I,PER_ALUGUEL_A,PER_ALUGUEL_E)
VALUES ('S','ACESSO TOTAL', 'S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S','S');

GO

DROP TABLE USUARIO;

GO

CREATE TABLE USUARIO (
ID INT PRIMARY KEY IDENTITY,
DATA_INC DATETIME,
DATA_ALT DATETIME,
STATUS CHAR(1),
MARCA CHAR(1),
USU_NOME VARCHAR(50),
USU_DEPARTAMENTO VARCHAR(100),
USU_LOGIN VARCHAR(10),
USU_SENHA VARCHAR(10),
USU_ID_PERFIL INT
)

GO

--Inserindo usuário de teste com todas as permissões liberadas (Login: TESTE / Senha: 123)
INSERT INTO USUARIO (STATUS, USU_NOME, USU_DEPARTAMENTO, USU_LOGIN, USU_SENHA, USU_ID_PERFIL) VALUES ('S','TESTE', 'DEP01', 'TESTE', '123', 1);

GO

DROP TABLE MARCA;

GO

CREATE TABLE MARCA (
ID INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(30) NOT NULL,
DATA_INC DATETIME,
DATA_ALT DATETIME,
STATUS CHAR(1) NOT NULL
)

GO

DROP TABLE CATEGORIA;

GO

CREATE TABLE CATEGORIA (
ID INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(30) NOT NULL,
DATA_INC DATETIME,
DATA_ALT DATETIME,
STATUS CHAR(1) NOT NULL
)

GO

DROP TABLE FORNECEDOR;

GO

CREATE TABLE FORNECEDOR (
ID INT PRIMARY KEY IDENTITY,
RAZAO_SOCIAL VARCHAR(50) NOT NULL,
NOME_FANTASIA VARCHAR(50),
CNPJ VARCHAR(18) NOT NULL, --00.000.000/0000-00
IE VARCHAR(15) NOT NULL, --000.000.000.000
LOGRADOURO VARCHAR(20) NOT NULL,
NOME_LOGRADOURO VARCHAR(50) NOT NULL,
NUM INT NOT NULL,
COMPLEMENTO VARCHAR(20),
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(40) NOT NULL,
ESTADO CHAR(2) NOT NULL,
TELEFONE VARCHAR(13), --(00)0000-0000
CELULAR VARCHAR(14), --(00)00000-0000
EMAIL VARCHAR(50),
CONTATO VARCHAR(50),
DATA_INC DATETIME,
DATA_ALT DATETIME,
STATUS CHAR(1) NOT NULL
)

GO

DROP TABLE PRODUTO;

GO

CREATE TABLE PRODUTO (
ID INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(50) NOT NULL,
CD_INTERNO VARCHAR(10) NOT NULL,
VALOR_DIARIA FLOAT NOT NULL,
STATUS CHAR(1) NOT NULL,
DISPONIVEL CHAR(1),
CARACTERISTICAS VARCHAR(MAX),
CD_MARCA INT NOT NULL,
CD_CATEGORIA INT NOT NULL,
CD_FORNECEDOR INT NOT NULL,
DATA_INC DATETIME,
DATA_ALT DATETIME,
CONSTRAINT FK_MARCA FOREIGN KEY(CD_MARCA) REFERENCES MARCA(ID),
CONSTRAINT FK_CATEGORIA FOREIGN KEY(CD_CATEGORIA) REFERENCES CATEGORIA(ID),
CONSTRAINT FK_FORNECEDOR FOREIGN KEY(CD_FORNECEDOR) REFERENCES FORNECEDOR(ID)
)

GO

DROP TABLE CLIENTE;

GO

CREATE TABLE CLIENTE (
ID INT PRIMARY KEY IDENTITY,
TIPO_PESSOA CHAR(1) NOT NULL,
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(14), --000.000.000-00
RG VARCHAR(12), --00.000.000-0
CNPJ VARCHAR(18), --00.000.000/0000-00
IE VARCHAR(15), --000.000.000.000
LOGRADOURO VARCHAR(20) NOT NULL,
NOME_LOGRADOURO VARCHAR(50) NOT NULL,
NUM INT NOT NULL,
COMPLEMENTO VARCHAR(20),
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(40) NOT NULL,
ESTADO CHAR(2) NOT NULL,
TELEFONE VARCHAR(13), --(00)0000-0000
CELULAR VARCHAR(14), --(00)00000-0000
EMAIL VARCHAR(50),
DATA_INC DATETIME,
DATA_ALT DATETIME,
STATUS CHAR(1) NOT NULL
)

GO

DROP TABLE ALUGUEL;

GO

CREATE TABLE ALUGUEL (
ID INT PRIMARY KEY IDENTITY,
DT_REGISTRO DATETIME,
SUBTOTAL FLOAT,
TOTAL_MULTA FLOAT,
TOTAL FLOAT,
CD_CLIENTE INT,
CD_PRODUTO INT,
CD_USUARIO INT,
DATA_INC DATETIME,
DATA_ALT DATETIME,
CONSTRAINT FK_CLIENTE FOREIGN KEY(CD_CLIENTE) REFERENCES CLIENTE(ID),
CONSTRAINT FK_PRODUTO FOREIGN KEY(CD_PRODUTO) REFERENCES PRODUTO(ID),
CONSTRAINT FK_USUARIO FOREIGN KEY(CD_USUARIO) REFERENCES USUARIO(ID)
)

GO

DROP TABLE ITENSALUGUEL;

GO

CREATE TABLE ITENSALUGUEL (
ID INT PRIMARY KEY IDENTITY,
DT_LOCACAO DATE,
DT_DEVOLUCAO DATE,
QTDE_DIAS INT,
QTDE_DIAS_ATRASO INT,
VALOR_DIARIA FLOAT,
VALOR_MULTA FLOAT,
CD_ALUGUEL INT,
DATA_INC DATETIME,
DATA_ALT DATETIME,
CONSTRAINT FK_ALUGUEL FOREIGN KEY(CD_ALUGUEL) REFERENCES ALUGUEL(ID)
)